### ISSUE TITLE
Registration fails

### ISSUE THREAD

**Issue by aral** [staticland/staticland#13]
```
staticland register --server staticland.ind.ie
email: aral@ind.ie
password: ******************************************

undefined:1
<html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/staticland/index.js:157:63)
    at Request.self.callback (/usr/local/lib/node_modules/staticland/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/staticland/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/staticland/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
```

Tracing out the actual response: 

```
function request (opts, callback) {
    return req(opts, function (err, res, body) {

      console.log (body);
```

Returns:

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.13.0</center>
</body>
</html>
```

### nginx error log

```
…
2017/05/17 19:35:50 [error] 12475#12475: *37 upstream prematurely closed connection while reading response header from upstream, client: 81.170.232.150, server: staticland.ind.ie, request: "POST /accounts/register HTTP/1.1", upstream: "http://127.0.0.1:3322/accounts/register", host: "staticland.ind.ie"
```

### App log (from `forever logs index.js`)

```
data:    index.js:12979 - /home/ubuntu/staticland-api/node_modules/jwa/index.js:32
data:    index.js:12979 -       throw typeError(MSG_INVALID_SECRET);
data:    index.js:12979 -       ^
data:    index.js:12979 - TypeError: secret must be a string or buffer
data:    index.js:12979 -     at typeError (/home/ubuntu/staticland-api/node_modules/jwa/index.js:16:10)
data:    index.js:12979 -     at Object.sign (/home/ubuntu/staticland-api/node_modules/jwa/index.js:32:13)
data:    index.js:12979 -     at Object.jwsSign [as sign] (/home/ubuntu/staticland-api/node_modules/jws/lib/sign-stream.js:23:24)
data:    index.js:12979 -     at Object.module.exports [as sign] (/home/ubuntu/staticland-api/node_modules/jsonwebtoken/sign.js:151:16)
data:    index.js:12979 -     at Object.sign (/home/ubuntu/staticland-api/node_modules/township-token/index.js:74:16)
data:    index.js:12979 -     at /home/ubuntu/staticland-api/node_modules/township-accounts/index.js:80:29
data:    index.js:12979 -     at /home/ubuntu/staticland-api/node_modules/township-access/index.js:20:12
data:    index.js:12979 -     at /home/ubuntu/staticland-api/node_modules/levelup/lib/levelup.js:258:9
data:    index.js:12979 - error: Forever detected script exited with code: 1
data:    index.js:12979 - error: Script restart attempt #2
data:    index.js:12979 - listening on 127.0.0.1:3322
```

**Comment by aral** [comment]
Looks like the issue is that the secret is not set. I noticed something to that effect in the config.js when used in production (env var must be set) – not sure if I missed that in the installation instructions (will check). Going to try and set that and see if it fixes it.

**Comment by aral** [comment]
Right, it was the issue. It doesn’t look like that’s mentioned in the docs. Preparing a pull request now.

**Comment by aral** [comment]
Pull request: https://github.com/staticland/staticland-api/pull/14
