### ISSUE TITLE
Add option for excluding particular files/directories

### ISSUE THREAD

**Issue by jonhoo** [staticland/staticland#6]
I want to use `staticland` for hosting static prototypes of sites I'm building, but some of them also have large folders holding PDFs, ZIPs, etc, which I don't need to upload for preview purposes. Having an `--exclude` flag would be really useful!

**Comment by sethvincent** [comment]
Agreed. It used to read .gitignore and used that to ignore files, but I realized that sometimes I want to ignore things in git that I want to publish to the static site (built assets like css, etc.).

I was thinking about a .staticlandignore file but like to minimize the number of files like that in a repo.

Adding an `--exclude` option sounds like a good idea.

**Comment by sethvincent** [comment]
OK, there's now an `--exclude` option as of v3.0.0.

Here's an example using the short alias `-e`:

```sh
staticland site/ example.com -e bigfile.pdf -e secret.txt -e dir/of/super/big/files/
```

**Comment by jonhoo** [comment]
so the `-e` is relative to the given `--path`, not relative to the current directory?

**Comment by jonhoo** [comment]
also, I get some weird errors when using `-e`:
```console
$ staticland -e papers _site/ domain
undefined:1
<html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/lib/node_modules/staticland/index.js:80:48)
    at Request.self.callback (/usr/lib/node_modules/staticland/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/staticland/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/staticland/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:292:16)
```

**Comment by sethvincent** [comment]
@jonhoo it should be relative to the source path, `_site/` in this case.

**Comment by sethvincent** [comment]
ok latest staticland (v3.0.5) should now have a fix for that `-e` bug. It wasn't getting passed through to the deploy function properly in shorthand mode.

**Comment by jonhoo** [comment]
v3.0.5 seems to work correctly :)

**Comment by sethvincent** [comment]
cool! 🎉
